### ISSUE TITLE
Malformed URL when running command in A CC computer

### ISSUE THREAD

**Issue by ObeseTermite** [MCJack123/remote.craftos-pc.cc#1]
When running the command to first get connected to VS code, when i paste the command into the computer it tries, then says "Malformed URL" and fails. I tried following the documentation again , reinstalling java, reinstalling the VS code addon, i tried everything. Im using CC 1.80 for minecraft 1.12.2. Im running a singleplayer world

**Comment by MCJack123** [comment]
remote.craftos-pc.cc requires CC: Tweaked. Please upgrade your version of CC.

At the moment, CC:T on Minecraft 1.12.2 is not supported; however, this will be fixed in the future.
