### ISSUE TITLE
Cannot GET & Certificate Expired

### ISSUE THREAD

**Issue by TheIncgi** [MCJack123/remote.craftos-pc.cc#3]
It looks like the LetsEncrypt Certificate expired for `https://remote.craftos-pc.cc/`

The URLs generated don't seem to work, in CC `wget` fails to load the anything from the URL
In browser (with a new link) results come back like `Cannot GET /server.lua%20oWl-kTU1whiFjXG8yM75QjmvPrJeXbvQti4d5PQT`.

**Comment by MCJack123** [comment]
Argh, certbot really annoys me sometimes.
